#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "matrix-puppet-discord"
name = "Matrix-Discord bridge"
description.en = "Discord puppeting bridge for Matrix/Synapse."
description.fr = "Passerelle Discord pour Matrix/Synapse."

version = "0.1.7~ynh5"

maintainers = ["fflorent"]

[upstream]
license = "Apache-2.0"
admindoc = "https://gitlab.com/mx-puppet/discord/mx-puppet-discord"
code = "https://gitlab.com/mx-puppet/discord/mx-puppet-discord"
fund = "https://liberapay.com/Sorunome/donate"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_releant"
sso = "not_releant"
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

    [install.synapsenumber]
    ask.en = "Choose the local synapse instance number to communicate with the Discord-Matrix bridge"
    ask.fr = "Choisissez le numéro de l'instance synapse qui doit communiquer avec la passerelle Discord-Matrix"
    help.en = "If you installed synapse only once time, then leave default value 1."
    help.fr = "Si vous n'avez installé qu'une fois synapse, gardez la valeur par défaut 1."
    type = "string"
    example = "2 (for instance synapse__2)"
    default = "1"

[resources]
    [resources.sources.main]
    url = "https://gitlab.com/mx-puppet/discord/mx-puppet-discord/-/archive/fd4402268e9a8b942ca632f3337702862e06d24f/mx-puppet-discord-master.tar.gz"
    sha256 = "b0edc4dfe9d3670eb8b53dc229a8fd7fb794ada5fe1f3d3ba4c38b54ce5ca176"

    autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.ports]

    [resources.apt]
    packages = [
        "postgresql",
        "libcairo2-dev",
        "libpango1.0-dev",
        "libjpeg-dev",
        "libgif-dev",
        "librsvg2-dev",
    ]

    [resources.database]
    type = "postgresql"
