#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    preinstall = """
        sudo yunohost tools update apps
        sudo yunohost app install https://github.com/YunoHost-Apps/synapse_ynh/ \
        -a "domain=$domain&server_name=$server_name&is_free_registration=$is_free_registration&jitsi_server=$jitsi_server" --force
    """

    # ------------
    # Tests to run
    # ------------

    # domain="domain.tld"
    # port="8343"
    # synapsenumber=1
