# You can edit this file.
# This will override the configuration contained in the __INSTALL_DIR__/base.config.yaml file.
# Don't hesitate to take a look at __INSTALL_DIR__/sample.config.yaml to see all the available options.
# Then, in order to take into account the changes, run: systemctl restart __APP__

provisioning:
  # Regex of Matrix IDs allowed to use the puppet bridge
  whitelist:
    # Allow a specific user
    #- "@user:server\\.com"

    # Allow users on a specific homeserver
    - '__ANY_ACCOUNT_OF_DOMAIN__'

    # Allow anyone
    #- ".*"

  # Regex of Matrix IDs forbidden from using the puppet bridge
  #blacklist:
    # Disallow a specific user
    #- "@user:server\\.com"

    # Disallow users on a specific homeserver
    #- "@.*:server\\.com"

relay:
  # Regex of Matrix IDs who are allowed to use the bridge in relay mode.
  # Relay mode is when a single Discord bot account relays messages of
  # multiple Matrix users
  #
  # Same format as in provisioning
  whitelist:
    - '__ANY_ACCOUNT_OF_DOMAIN__'

  #blacklist:
    #- "@user:yourserver\\.com"

selfService:
  # Regex of Matrix IDs who are allowed to use bridge self-servicing (plumbed rooms)
  #
  # Same format as in provisioning
  whitelist:
    - '__ANY_ACCOUNT_OF_DOMAIN__'

  #blacklist:
    #- "@user:server\\.com"

